### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by MarcDrexler** [martinpeck/AppInsights.grpc#8]
Hi Martin,
i just found that project and I wonder if this is still working and if it is still the way how we can get grpc client-server correlation into application insights?
Are you still using this approach?
I couldn't find something else for .NET Framework Clients and NET Core Server.

Thanks
Marc

**Comment by martinpeck** [comment]
Wow...I should have replied WAY earlier than this.
Sorry...no, it's not (but you probably guessed this already).
I will mark this project as archived.
